
DROP TABLE public.residential_prop_chars;

CREATE TABLE public.residential_prop_chars
(
  id integer NOT NULL DEFAULT nextval('residential_prop_chars_id_seq'::regclass),
  pin character varying(25),
  schednum bigint,
  cd integer,
  ofcard integer,
  owner character varying(250),
  co_owner character varying(250),
  owner_num integer,
  owner_dir character varying(25),
  owner_st character varying(250),
  owner_type character varying(250),
  owner_apt character varying(250),
  owner_city character varying(250),
  owner_state character varying(250),
  owner_zip character varying(250),
  site_nbr integer,
  site_dir character varying(250),
  site_name character varying(250),
  site_mode character varying(250),
  site_more character varying(250),
  tax_dist character varying(250),
  prop_class integer,
  property_class character varying(250),
  zone10 character varying(250),
  d_class_cn character varying(250),
  land_sqft integer,
  area_abg integer,
  bsmt_area integer,
  fbsmt_sqft integer,
  grd_area integer,
  story integer,
  style_cn character varying(250),
  bed_rms integer,
  full_b integer,
  hlf_b integer,
  ccyrblt integer,
  ccage_rm integer,
  units integer,
  asmt_appr_land integer,
  total_value integer,
  asdland integer,
  assess_value integer,
  asmt_taxable integer,
  asmt_exempt_amt integer,
  nbhd_1 integer,
  nbhd_1_cn character varying(250),
  legl_description character varying(250),
  CONSTRAINT residential_prop_chars_pkey PRIMARY KEY (id)
)
